Add sound support Fix asset change detection

diff --git a/build/android/Makefile b/build/android/Makefile
--- a/build/android/Makefile
+++ b/build/android/Makefile
@@ -15,8 +15,19 @@ ASSETS_TIMESTAMP = deps/assets_timestamp
 
 LEVELDB_DIR = $(ROOT)/deps/leveldb/
 LEVELDB_LIB = $(LEVELDB_DIR)libleveldb.a
-LEVELDB_TIMESTAMP = $(LEVELDB_DIR)timestamp
+LEVELDB_TIMESTAMP = $(LEVELDB_DIR)/timestamp
 LEVELDB_TIMESTAMP_INT = $(ROOT)/deps/leveldb_timestamp
+
+OPENAL_DIR = $(ROOT)/deps/openal-soft/
+OPENAL_LIB = libs/armeabi/libopenal.so
+OPENAL_TIMESTAMP = $(OPENAL_DIR)/timestamp
+OPENAL_TIMESTAMP_INT = $(ROOT)/deps/openal_timestamp
+
+OGG_DIR = $(ROOT)/deps/libvorbis-libogg-android/
+OGG_LIB = libs/armeabi/libogg.so
+VORBIS_LIB = libs/armeabi/libogg.so
+OGG_TIMESTAMP = $(OGG_DIR)timestamp
+OGG_TIMESTAMP_INT = $(ROOT)/deps/ogg_timestamp
 
 IRRLICHT_DIR = $(ROOT)/deps/irrlicht/
 IRRLICHT_LIB = $(IRRLICHT_DIR)lib/Android/libIrrlicht.a
@@ -25,8 +36,8 @@ IRRLICHT_TIMESTAMP_INT = $(ROOT)/deps/irrlicht_timestamp
 
 CURL_VERSION = 7.35.0
 CURL_DIR = $(ROOT)/deps/curl-$(CURL_VERSION)
-CURL_LIB = $(CURL_DIR)lib/.libs/libcurl.a
-CURL_TIMESTAMP = $(CURL_DIR)timestamp
+CURL_LIB = $(CURL_DIR)/lib/.libs/libcurl.a
+CURL_TIMESTAMP = $(CURL_DIR)/timestamp
 CURL_TIMESTAMP_INT = $(ROOT)/deps/curl_timestamp
 
 
@@ -37,7 +48,7 @@ OGLES2_SHADER_PATH=\"/sdcard/Minetest/media/Shaders/\"
 .PHONY : debug release reconfig delconfig \
 	leveldb_download clean_leveldb leveldb\
 	irrlicht_download clean_irrlicht irrlicht \
-	clean_assets assets $(ASSETS_TIMESTAMP) \
+	clean_assets assets \
 	apk_debug apk_release clean_apk \
 	clean_all clean prep_srcdir \
 	install_debug install envpaths all
@@ -78,7 +89,86 @@ $(PATHCFGFILE) :
 	fi;                                                                        \
 	echo "SDKFOLDER = $$SDKFLDR" >> ${PATHCFGFILE};
 
+$(OPENAL_TIMESTAMP) : openal_download
+	@LAST_MODIF=$$(find ${OPENAL_DIR} -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
+		touch ${OPENAL_TIMESTAMP};                                            \
+	fi
+	
+openal_download :
+	@if [ ! -d ${OPENAL_DIR} ] ; then                                          \
+		echo "openal sources missing, downloading...";                         \
+		mkdir -p ${ROOT}/deps;                                                 \
+		cd ${ROOT}/deps ;                                                      \
+		git clone https://github.com/apportable/openal-soft || exit 1;         \
+	fi
+	
+openal : $(OPENAL_LIB)
 
+$(OPENAL_LIB): $(OPENAL_TIMESTAMP)
+	@REFRESH=0;                                                                \
+	if [ ! -e ${OPENAL_TIMESTAMP_INT} ] ; then                                 \
+		REFRESH=1;                                                             \
+	fi;                                                                        \
+	if [ ${OPENAL_TIMESTAMP} -nt ${OPENAL_TIMESTAMP_INT} ] ; then              \
+		REFRESH=1;                                                             \
+	fi;                                                                        \
+	if [ $$REFRESH -ne 0 ] ; then                                              \
+	export PATH=$$PATH:${SDKFOLDER}/platform-tools:${ANDROID_NDK};             \
+	echo "changed timestamp for openal detected building...";                  \
+	cd ${OPENAL_DIR};                                                          \
+	ndk-build NDEBUD=${NDEBUG} NDK_MODULE_PATH=${NDK_MODULE_PATH} ${PARALLEL} || exit 1;\
+	cp ${OPENAL_DIR}/libs/armeabi/libopenal.so $(ROOT)/libs/armeabi/libopenal.so;\
+	touch ${OPENAL_TIMESTAMP};                                                 \
+	touch ${OPENAL_TIMESTAMP_INT};                                             \
+	else                                                                       \
+		echo "nothing to be done for openal";                                  \
+	fi
+	
+clean_openal :
+	$(RM) -rf ${OPENAL_DIR}
+	
+$(OGG_TIMESTAMP) : ogg_download
+	@LAST_MODIF=$$(find ${OGG_DIR} -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
+		touch ${OGG_TIMESTAMP};                                                \
+	fi
+	
+ogg_download :
+	@if [ ! -d ${OGG_DIR} ] ; then                                             \
+		echo "openal sources missing, downloading...";                         \
+		mkdir -p ${ROOT}/deps;                                                 \
+		cd ${ROOT}/deps ;                                                      \
+		git clone https://github.com/vincentjames501/libvorbis-libogg-android|| exit 1;\
+	fi
+	
+ogg : $(OGG_LIB)
+
+$(OGG_LIB): $(OGG_TIMESTAMP)
+	@REFRESH=0;                                                                \
+	if [ ! -e ${OGG_TIMESTAMP_INT} ] ; then                                    \
+		echo "${OGG_TIMESTAMP_INT} doesn't exist";                             \
+		REFRESH=1;                                                             \
+	fi;                                                                        \
+	if [ ${OGG_TIMESTAMP} -nt ${OGG_TIMESTAMP_INT} ] ; then                    \
+		echo "internal newer";                                                 \
+		REFRESH=1;                                                             \
+	fi;                                                                        \
+	if [ $$REFRESH -ne 0 ] ; then                                              \
+	export PATH=$$PATH:${SDKFOLDER}/platform-tools:${ANDROID_NDK};             \
+	echo "changed timestamp for ogg detected building...";                     \
+	cd ${OGG_DIR};                                                             \
+	ndk-build NDEBUD=${NDEBUG} NDK_MODULE_PATH=${NDK_MODULE_PATH} ${PARALLEL} APP_ABI=armeabi || exit 1;\
+	cp ${OGG_DIR}/libs/armeabi/libogg.so $(ROOT)/libs/armeabi/libogg.so;       \
+	cp ${OGG_DIR}/libs/armeabi/libvorbis.so $(ROOT)/libs/armeabi/libvorbis.so; \
+	touch ${OGG_TIMESTAMP};                                                    \
+	touch ${OGG_TIMESTAMP_INT};                                                \
+	else                                                                       \
+		echo "nothing to be done for libogg/libvorbis";                        \
+	fi
+
+clean_ogg :
+	$(RM) -rf ${OGG_DIR}
 
 $(LEVELDB_TIMESTAMP) : leveldb_download
 	@LAST_MODIF=$$(find ${LEVELDB_DIR} -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
@@ -226,48 +316,48 @@ clean_curl :
 $(ASSETS_TIMESTAMP) :
 	@mkdir -p ${ROOT}/deps;                                                     \
 	LAST_MODIF=$$(find ${ROOT}/../../builtin -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
-	if [ $$LAST_MODIF != "timestamp" ] ; then                                  \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
 		touch ${ROOT}/../../builtin/timestamp;                                 \
 		touch ${ASSETS_TIMESTAMP};                                             \
-		echo builtin changed;                                                  \
+		echo builtin changed $$LAST_MODIF;                                     \
 	fi;                                                                        \
 	LAST_MODIF=$$(find ${ROOT}/../../client -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
-	if [ $$LAST_MODIF != "timestamp" ] ; then                                  \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
 		touch ${ROOT}/../../client/timestamp;                                  \
 		touch ${ASSETS_TIMESTAMP};                                             \
 	fi;                                                                        \
 	LAST_MODIF=$$(find ${ROOT}/../../doc -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
-	if [ $$LAST_MODIF != "timestamp" ] ; then                                  \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
 		touch ${ROOT}/../../doc/timestamp;                                     \
 		touch ${ASSETS_TIMESTAMP};                                             \
 	fi;                                                                        \
 	LAST_MODIF=$$(find ${ROOT}/../../fonts -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
-	if [ $$LAST_MODIF != "timestamp" ] ; then                                  \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
 		touch ${ROOT}/../../fonts/timestamp;                                   \
 		touch ${ASSETS_TIMESTAMP};                                             \
 	fi;                                                                        \
 	LAST_MODIF=$$(find ${ROOT}/../../games -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
-	if [ $$LAST_MODIF != "timestamp" ] ; then                                  \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
 		touch ${ROOT}/../../games/timestamp;                                   \
 		touch ${ASSETS_TIMESTAMP};                                             \
 	fi;                                                                        \
 	LAST_MODIF=$$(find ${ROOT}/../../mods -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
-	if [ $$LAST_MODIF != "timestamp" ] ; then                                  \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
 		touch ${ROOT}/../../mods/timestamp;                                    \
 		touch ${ASSETS_TIMESTAMP};                                             \
 	fi;                                                                        \
 	LAST_MODIF=$$(find ${ROOT}/../../po -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
-	if [ $$LAST_MODIF != "timestamp" ] ; then                                  \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
 		touch ${ROOT}/../../po/timestamp;                                      \
 		touch ${ASSETS_TIMESTAMP};                                             \
 	fi;                                                                        \
 	LAST_MODIF=$$(find ${ROOT}/../../textures -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
-	if [ $$LAST_MODIF != "timestamp" ] ; then                                  \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
 		touch ${ROOT}/../../textures/timestamp;                                \
 		touch ${ASSETS_TIMESTAMP};                                             \
 	fi;                                                                        \
 	LAST_MODIF=$$(find ${IRRLICHT_DIR}/media -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "); \
-	if [ $$LAST_MODIF != "timestamp" ] ; then                                  \
+	if [ $$(basename $$LAST_MODIF) != "timestamp" ] ; then                     \
 		touch ${IRRLICHT_DIR}/media/timestamp;                                 \
 		touch ${ASSETS_TIMESTAMP};                                             \
 	fi;                                                                        \
@@ -314,12 +404,15 @@ assets : $(ASSETS_TIMESTAMP)
 	find . -name "timestamp" -exec rm {} \; ;                                  \
 	ls -R | grep ":$$" | sed -e 's/:$$//' -e 's/\.//' -e 's/^\///' > "index.txt"; \
 	cp ${ROOT}/${ASSETS_TIMESTAMP} ${ROOT}/${ASSETS_TIMESTAMP}.old;            \
+	else                                                                       \
+		echo "nothing to be done for assets";                                  \
 	fi
 
 clean_assets :
 	@$(RM) -r assets
 	
-apk_debug: $(PATHCFGFILE) assets $(LEVELDB_LIB) irrlicht prep_srcdir
+apk_debug: $(PATHCFGFILE) assets $(LEVELDB_LIB) $(IRRLICHT_LIB) $(CURL_LIB) \
+	$(OPENAL_LIB) $(OGG_LIB) prep_srcdir
 	@export PATH=$$PATH:${SDKFOLDER}/platform-tools:${ANDROID_NDK};            \
 	export ANDROID_HOME=${SDKFOLDER};                                          \
 	mkdir -p ${ROOT}/src;                                                      \
@@ -330,7 +423,8 @@ apk_debug: $(PATHCFGFILE) assets $(LEVELDB_LIB) irrlicht prep_srcdir
 	echo "APK: bin/Minetest-debug.apk" &&                                      \
 	echo "You can install it with \`adb install -r bin/Minetest-debug.apk\`"
 
-apk_release: $(PATHCFGFILE) assets $(LEVELDB_LIB) irrlicht prep_srcdir
+apk_release: $(PATHCFGFILE) assets $(LEVELDB_LIB) $(IRRLICHT_LIB) $(CURL_LIB) \
+	$(OPENAL_LIB) $(OGG_LIB) prep_srcdir
 	@export PATH=$$PATH:${SDKFOLDER}/platform-tools:${ANDROID_NDK};            \
 	export ANDROID_HOME=${SDKFOLDER};                                          \
 	mkdir -p ${ROOT}/src;                                                      \
